version: '3.8'

services:
  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Persist Redis data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
  tinyurl-service:
    build: .
    container_name: tinyurl-service
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo  
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/tinyUrl
    volumes:
      - .:/app
volumes:
  mongo_data: # Volume for MongoDB storage
  redis_data: # Volume for Redis storage
  project_data: # Volume for your project files
